name: number_guess_hangman
description: A simple number guessing hangman-style game built with Flutter.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2



  # new packages used for the playful UI/animation
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hangman.png
  fonts:
    - family: Marker
      fonts:
        - asset: fonts/marker.ttf

